name: Generate Contribution Snake 🐍

on:
  schedule:
    - cron: "0 18 * * *"  # Every day at 12:00 AM IST (6:30 PM UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SarthakNimse
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake-dark.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "⚡ Update GitHub Contribution Snake"
          add: "github-contribution-grid-snake.svg github-contribution-grid-snake-dark.svg"
